### PR TITLE
Add hook callbacks for rebase and merge operations

### PR DESCRIPTION
**Pull request by implausible**
This will help consumers of nodegit-flow that utilize GitHooks operations.

### CODE REVIEW

**Comment by smith-kyle** [comment]
We should probably update the docs

**Comment by implausible** [comment]
oops

**Comment by implausible** [comment]
Note https://github.com/nodegit/nodegit/pull/1224 is a requirement for the beforeRebaseFinishCallback to be called. Without that the beforeRebaseFinishCallback will just never be called.

**Comment by smith-kyle** [comment]
Good to know! Since `beforeRebaseFinishCallback` is optional and this module doesn't require a specific version of nodegit it's no big deal

**Pull request merged**
